{% set name = "iminuit" %}
{% set version = "2.31.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ffb3aeb2de26c400d0aff7e2b7457f64cd609a494c45ee579effee81b1bc5d78

build:
  number: 0
  script:
    - export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}  # [unix]
    - set CMAKE_BUILD_PARALLEL_LEVEL=%CPU_COUNT%      # [win]
    - set CMAKE_GENERATOR=Ninja                       # [win]
    - {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja-base  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy {{ numpy }}
    # pybind11 >=3 is not in the main channel
    - pybind11 >=2.13.6
    - scikit-build-core >=0.11
  run:
    - python
    - numpy >=1.21

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip
  imports:
    - iminuit
  commands:
    - python -m pytest tests
    - pip check

about:
  home: https://github.com/scikit-hep/iminuit
  license: LGPL-2.1-or-later AND MIT
  license_family: LGPL
  license_file: LICENSE
  summary: Interactive Minimization Tools based on MINUIT
  description: |
    iminuit is designed from ground up to be fast, interactive and cython
    friendly. iminuit extract function signature very permissively starting
    from checking func_code down to last resort of parsing docstring (or you
    could tell iminuit to stop looking and take your answer). The interface is
    inspired heavily by PyMinuit and the status printout is inspired by ROOT
    Minuit. iminuit is mostly compatible with PyMinuit (with few exceptions).
    Existing PyMinuit code can be ported to iminuit by just changing the
    import statement.
  doc_url: https://iminuit.readthedocs.io
  dev_url: https://github.com/scikit-hep/iminuit

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - piti118
    - HDembinski
    - chrisburr
    - henryiii
