travis:
  secure:
    BINSTAR_TOKEN: pPLneox/Zi3Bn6fPiFsL0CXkeDy12d2KE8CJAWUOp7nRi0FJZ64ud6bvFppH093sRHpGsU3Xt1B/27uXYk+Qtrs4kP6OimWbXWSR/J3nzCx6WOb7tdPThwYqUlM2uSYOOkLTIA/DJwRdmXogle6d7d8P8bMir6Z/xtNi2Gl8K66B3QtCsf+fKPDivCpneu+cguSPEH9cUfGrz/JxWsK5++7fwV+r6lJWNalhlez8J+kGPUlU2MGFDhpJ94RmY4u/nu+JKAdLydb7L9qauiOT/mIliFD2XDzDyWZoGJPnQr96AmHa+EfEHzlclw9Fifv3VL0K9pJZCyLDecA6lrWJUn/HVUX0lC380moFa6UgEtsiGSHoDEZTjFueYd7uKmLGuytG1U8HDFZ6qcDxoLNFLvYuQVelPyw2UBIhnbW9GIzwgVgZ7RcJpk8bBUtVpxJ6jz8O36FXyjndWcFnaBU9Qn3vlysnZT6RWVe3SEhdc6RVk6w3MXP+XIovMqS8Md2TW2FcwzdBBjyRdrgZwHt0iCWj0UI8lO7xnawL50j9zOch1WOKrss0LJH2SvaXrYOHFdvjDzgxLXNj8LOTou6mGt18GYHaLoy8DsKxRCatvEkNxfN3QotadBd/yHcCyVb9qoMNZHEVnqMEz7VFvYko/1Ck1QroTFRWzoDQvwwcuH0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
